// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Data;
using Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Data.Configurations
{
    public partial class StudentConfiguration : IEntityTypeConfiguration<Student>
    {
        public void Configure(EntityTypeBuilder<Student> entity)
        {
            entity.Property(e => e.ClassName).HasMaxLength(50);

            entity.HasOne(d => d.Course).WithMany(p => p.Student)
            .HasForeignKey(d => d.CourseId)
            .HasConstraintName("FK_Course_Student");

            entity.HasOne(d => d.Person).WithMany(p => p.Student)
            .HasForeignKey(d => d.PersonId)
            .HasConstraintName("FK_Person_Student");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Student> entity);
    }
}
